version: "3.7"
services:
    redis:
        container_name: "redis-cache"
        image: redis
        ports:
            - '6379:6379'
        restart: always
        networks: 
            - default

    cloudwalk:
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - 8080:8080
        networks:
            - default
        depends_on:
            - redis